name: esol
version: 1.0.0
description: A new Flutter project.
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  adobe_xd: ^1.0.0+1
  flushbar: ^1.10.4
  flutter_platform_widgets: ^0.60.1
  enum_to_string: ^1.0.11
  local_auth: ^0.6.2+3
  auto_size_text: ^2.1.0
  flutter_webview_plugin: ^0.3.11
  phone_number: ^0.6.2+4
  libphonenumber: ^1.0.1
  cached_network_image: ^2.3.2+1
  rate_my_app: ^0.6.1+7
  auto_route: ^0.6.6
  url_launcher: ^5.5.0
  http: ^0.12.0+4
  google_maps_flutter: ^0.5.28+1
  equatable: ^1.2.2
  shared_preferences: ^0.5.6+3
  package_info: ^0.4.1
  share: ^0.6.4+3
  flutter_svg: ^0.18.0
  cupertino_icons: ^0.1.3
  flutter_secure_storage: ^3.3.3
  flutter_redux: ^0.6.0
  flutter_dotenv: ^2.1.0
  redux_thunk: ^0.3.0
  redux_logging: ^0.4.0
  redux_persist: ^0.8.4
  country_code_picker: ^1.4.0
  wallet_core: ^0.2.4+11
  # native_screenshot:
  # wallet_core:
  # path: ../wallet_core
  barcode_scan: ^3.0.1
  flutter_slidable: ^0.5.4
  contacts_service: ^0.4.6
  permission_handler: ^5.0.1+1
  virtual_keyboard: ^0.1.4
  qr_flutter: ^3.2.0
  logger_flutter: ^0.7.1
  path_provider: ^1.6.14
  json_annotation: ^3.0.1
  pin_input_text_field: ^3.1.1
  flare_flutter: ^2.0.1
  decimal: ^0.3.5
  flutter_segment: 2.1.1
  firebase_messaging: ^7.0.0
  firebase_auth: ^0.18.0+1
  ethereum_address: ^1.0.1
  sentry: ^3.0.1
  device_info: '>=0.4.2+6 <2.0.0'
  image_picker: ^0.6.7+7
  flutter_cupertino_localizations: ^1.0.1
  flutter_branch_sdk: ^1.1.0
  flutter_udid: ^1.0.1
  flutter_camera_ml_vision: ^2.2.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  auto_route_generator: ^0.6.6
  flutter_native_splash: ^0.1.9
  dependency_validator: ^1.5.0
  flutter_launcher_icons: ^0.7.5
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  native_screenshot:
    path: ../
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: assets/images/app_icon.png
  android: true
  ios: true
flutter:
  assets:
    - i18n/
    - environment/.env
    - environment/.env_prod
    - environment/.env_qa
    - assets/
    - assets/images/
    - assets/images/animation.gif
  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Exo-ExtraLightItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Exo-Light.ttf
          weight: 300
        - asset: assets/fonts/Exo-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Exo-Black.ttf
          weight: 400
        - asset: assets/fonts/Exo-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Exo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Exo-ExtraBoldItalic.ttf
          style: italic
          weight: 900
  uses-material-design: true
